import React from 'react';
import './global.css';
import { ApolloWrapper } from './ApolloWarpper';

export const metadata = {
  title: 'Welcome to flavorful-symphonies',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-red-900">
        <ApolloWrapper>{children}</ApolloWrapper>
      </body>
    </html>
  );
}
