import React from 'react';
import { ApolloProvider } from '@apollo/client';
import './global.css';
import { apolloClient } from '@flavorful-symphonies/shared-core';

export const metadata = {
  title: 'Welcome to flavorful-symphonies',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-red-900">
        <ApolloProvider client={apolloClient}>{children}</ApolloProvider>
      </body>
    </html>
  );
}
